export const liveEngineLabel = 'App annual planning engine';
export const modelSources = [
  { id: 'scott', name: 'Expansion Model-2026-v1', owner: 'Scott’s Model', kind: 'Financial workbook · CSV reconstruction', status: 'Editable reconstruction · baseline reconciled', use: '1-HUB and S+U CSV exports drive a separate editable annual module and funding-target view. Not a live Excel connection.', assumptions: 'Annual expense lines are independent fixed-dollar inputs; only positive operating profit is shared. S+U targets are separate inputs × target margin, not cost-derived forecasts. Original scaling, ramp, depreciation and IRR formulas were not supplied.' },
  { id: 'laci', name: 'ARCHINNOVO Site Analysis', owner: 'LACI Model', kind: 'Site feasibility analysis', status: 'Read-only preliminary reference', use: 'LA screening scores, capacity, retained-revenue thresholds and source decisions, transcribed via Microhub_Viability_Scorecard (3).pdf.', assumptions: 'First draft September 2, 2026; $20/order retained revenue and $1M capital cap. Source Go is not B-Line approval. Original workbook filename/version not recorded.' },
  { id: 'holistic', name: 'Seattle_Hub_Holistic_Model.pdf', owner: 'Owner / workbook lineage to confirm', kind: 'Monthly financial-model snapshot', status: 'Read-only published results', use: 'Published annual results and comparison against the app engine. Not used to calculate editable scenarios.', assumptions: '36 months; July 2027 launch; equipment by June 2027; EBITDA, depreciation and loss-recouped profit sharing. Relationship to Scott’s workbook is unconfirmed.' },
  { id: 'scorecard', name: 'Microhub_Viability_Scorecard (3).pdf', owner: 'B-Line viability reference · owner to confirm', kind: 'Site scorecard snapshot', status: 'Read-only reference + explicit site copies', use: 'Seattle weighted rubric and desk estimates; also carries LA screening references. Source-site copying is opt-in.', assumptions: 'October 7, 2026 snapshot; Seattle evidence update cells blank. Unknown rent, NNN/CAM and site gates stay unvalidated.' },
  { id: 'module', name: '1-Hub module / Sources & Uses reference', owner: 'Scott’s Model · 1-Hub / S+U', kind: 'Separate financial reference', status: 'Reference arithmetic only', use: 'Occupancy ceilings and module economics in the source audit; not the active scenario engine.', assumptions: '$500k annual revenue, $90k rent, 20% profit share and 7% pre-share target margin. $500k all-grant funding is an assumption, not an award.' },
  { id: 'legacy', name: 'Legacy model · IS-Consol / Check-Op', owner: 'Owner / original file to confirm', kind: 'Legacy workbook notes', status: 'Unreconciled · not a baseline', use: 'Caveats only; no live calculation feed.', assumptions: 'IS-Consol does not tie to Check-Op. Expense labeling and reconciliation require review before reuse.' },
  { id: 'cityfi', name: 'Original Cityfi / user site scores', owner: 'Original site-record provenance to confirm', kind: 'Seeded / editable site records', status: 'Separate scoring scale', use: 'Original site records retain scores such as 25/24. These are not ARCHINNOVO /100 scores.', assumptions: 'Original source file, score scale and evidence dates need confirmation; user edits are local.' },
  { id: 'map', name: 'Cascadia Hub Map (4).html', owner: 'Owner to confirm', kind: 'Interactive map reference', status: 'Preserved reference', use: 'City, operator-market, sequencing and candidate-site context; not a financial data feed.', assumptions: 'Dated source snapshot, not a live market-data connection.' },
  { id: 'prep', name: 'Seattle microhub expansion prep and meetings - Claude.pdf', owner: 'Meeting / AI-prep context', kind: 'Supporting document', status: 'Context only', use: 'Attached planning context, not an approved calculation model or automatic data feed.', assumptions: 'Confirm recommendations and evidence with the team before treating them as approved inputs.' },
];
