import { useState } from 'react';
import { Download, Search, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useWorkspace, download } from '@/lib/workspace';
import { fields, type Metadata } from '@/lib/defaults';
import { Panel } from '@/components/Financials';
import { AssumptionInput } from '@/components/AssumptionInput';
export default function Assumptions() {
  const { active, setData } = useWorkspace();
  const [query, setQuery] = useState(''), [onlyValidation, setOnlyValidation] = useState(false);
  const filtered = fields.filter(f => `${f.label} ${f.group} ${f.unit} ${active.metadata[f.key].source}`.toLowerCase().includes(query.toLowerCase()) && (!onlyValidation || active.metadata[f.key].validation || f.validation));
  const edit = (key: string, values: Partial<Metadata>) => setData(w => ({ ...w, scenarios: w.scenarios.map(s => s.id === active.id ? { ...s, metadata: { ...s.metadata, [key]: { ...s.metadata[key], ...values } } } : s) }));
  const exportCsv = () => {
    const escape = (v: unknown) => { const text = String(v); return `"${(/^[=+\-@\t\r]/.test(text) ? "'" : '') + text.replace(/"/g, '""')}"`; };
    const rows = [['Scenario', 'Group', 'Input', 'Value', 'Unit', 'Source', 'Confidence', 'Needs validation'], ...fields.map(f => [active.name, f.group, f.label, active.inputs[f.key], f.unit, active.metadata[f.key].source, active.metadata[f.key].confidence, active.metadata[f.key].validation || !!f.validation])];
    download('b-line-assumptions.csv', rows.map(r => r.map(escape).join(',')).join('\r\n'), 'text/csv;charset=utf-8');
  };
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><div className="eyebrow">Make uncertainty visible</div><h1 className="mt-2">The assumptions behind the plan.</h1><p className="mt-2 text-sm text-muted-foreground">Every editable model input, its source and how much we trust it. {active.name}.</p></div><Button className="rounded-xl text-xs font-semibold" onClick={exportCsv}><Download size={15} className="mr-2" />Export all as CSV</Button></div><div className="flex flex-wrap justify-between gap-3"><div className="relative w-full sm:w-96"><Search size={15} className="absolute left-3 top-3 text-muted-foreground" /><Input className="h-10 rounded-xl bg-white pl-9 text-xs" placeholder="Search assumptions, units or sources…" value={query} onChange={e => setQuery(e.target.value)} /></div><label className="flex items-center gap-2 text-xs text-muted-foreground"><input className="accent-teal-700" type="checkbox" checked={onlyValidation} onChange={e => setOnlyValidation(e.target.checked)} /><AlertTriangle size={14} />Needs validation only <span className="rounded-lg bg-secondary px-2 py-1">{filtered.length}</span></label></div><Panel className="overflow-x-auto"><table className="data-table min-w-[1080px]"><thead><tr><th className="w-[350px]">Assumption & value</th><th>Unit</th><th className="w-[300px]">Source</th><th>Confidence</th><th>Needs validation</th></tr></thead><tbody>{filtered.map(f => <tr key={f.key}><td><span className="mb-1 block text-[9px] uppercase tracking-widest text-teal-800">{f.group}</span><AssumptionInput field={f} compact /></td><td className="text-muted-foreground">{f.unit}</td><td><Input aria-label={`Source for ${f.label}`} className="h-9 rounded-lg text-xs" value={active.metadata[f.key].source} onChange={e => edit(f.key, { source: e.target.value })} /></td><td><select className="form-select" aria-label={`Confidence for ${f.label}`} value={active.metadata[f.key].confidence} onChange={e => edit(f.key, { confidence: e.target.value as Metadata['confidence'] })}>{['low', 'med', 'high'].map(c => <option key={c}>{c}</option>)}</select></td><td><label className="flex items-center gap-2"><input type="checkbox" className="accent-teal-700" disabled={f.validation} checked={active.metadata[f.key].validation || !!f.validation} onChange={e => edit(f.key, { validation: e.target.checked })} /><span className="text-xs text-muted-foreground">{f.validation ? 'Required' : 'Validate'}</span></label></td></tr>)}</tbody></table>{!filtered.length && <p className="p-6 text-sm text-muted-foreground">No matching assumptions.</p>}</Panel></div>;
}
