import { useState } from 'react';
import { useWorkspace } from '@/lib/workspace';
import { Panel, Pnl } from '@/components/Financials';
import { calculate, money } from '@/lib/calc';
import { fields } from '@/lib/defaults';
export default function Compare() {
  const { data, active } = useWorkspace();
  const [left, setLeft] = useState(active.id), [right, setRight] = useState(data.scenarios.find(s => s.id !== active.id)?.id ?? active.id);
  const a = data.scenarios.find(s => s.id === left) ?? active, b = data.scenarios.find(s => s.id === right) ?? active;
  const models = [calculate(a.inputs), calculate(b.inputs)];
  const rows = [{ label: 'Year 1 total cost · USD', values: models.map(m => money(m.year1Total)) }, { label: 'Operating break-even', values: models.map(m => m.breakEven ? `Year ${m.breakEven}` : '> 3 years') }, { label: 'Year 3 profit · USD', values: models.map(m => money(m.years[2].profit)) }, { label: 'Year 3 cumulative cash · USD', values: models.map(m => money(m.years[2].cumulative)) }];
  return <div className="space-y-6"><div><div className="eyebrow">Better decisions, side by side</div><h1 className="mt-2">Compare the possibilities.</h1><p className="mt-2 text-sm text-muted-foreground">Two independent scenarios. The same financial rules.</p></div><div className="grid gap-5 md:grid-cols-2">{[a, b].map((s, i) => <Panel key={i} className="p-5"><label className="text-xs text-muted-foreground">Scenario {i === 0 ? 'A' : 'B'}<select className="form-select mt-2 w-full font-semibold" value={s.id} onChange={e => (i === 0 ? setLeft : setRight)(e.target.value)}>{data.scenarios.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label></Panel>)}</div>{a.id === b.id && <p className="text-xs text-amber-800">Both selections are the same scenario. Choose another or duplicate a scenario to test changes.</p>}<Panel className="overflow-x-auto"><table className="data-table"><thead><tr><th>Calculated outcome</th><th>{a.name}</th><th>{b.name}</th></tr></thead><tbody>{rows.map(r => <tr key={r.label}><td>{r.label}</td>{r.values.map((v, i) => <td key={i} className="font-semibold">{v}</td>)}</tr>)}</tbody></table></Panel><div className="grid gap-5 xl:grid-cols-2"><Pnl inputs={a.inputs} /><Pnl inputs={b.inputs} /></div><Panel className="overflow-x-auto"><h2 className="p-5">Different assumptions</h2><table className="data-table"><thead><tr><th>Input</th><th>{a.name}</th><th>{b.name}</th></tr></thead><tbody>{fields.filter(f => a.inputs[f.key] !== b.inputs[f.key]).map(f => <tr key={f.key}><td>{f.label}</td><td>{String(a.inputs[f.key])} {f.unit}</td><td>{String(b.inputs[f.key])} {f.unit}</td></tr>)}</tbody></table>{fields.every(f => a.inputs[f.key] === b.inputs[f.key]) && <p className="px-5 pb-5 text-xs text-muted-foreground">All inputs are identical.</p>}</Panel></div>;
}
