import ScottFinancials from '@/components/ScottFinancials';
import ScottAssumptions from '@/components/ScottAssumptions';
import ModelSelector from '@/components/ModelSelector';
import { useState } from 'react';
import { Bike, Building2, Users, Package, Store, Wallet, AlertTriangle, ArrowRight } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Slider } from '@/components/ui/slider';
import { Button } from '@/components/ui/button';
import { useWorkspace } from '@/lib/workspace';
import { fields } from '@/lib/defaults';
import { calculate, money, n, sensitivity } from '@/lib/calc';
import { Panel, Pnl, Targets, Tornado } from '@/components/Financials';
import { AssumptionInput } from '@/components/AssumptionInput';
export default function HubModel() {
  const { active, updateInput } = useWorkspace();
  const m = calculate(active.inputs);
  const [tab, setTab] = useState('Space');
  const groups = [{ label: 'Space', icon: Building2 }, { label: 'Fleet', icon: Bike }, { label: 'Labor', icon: Users }, { label: 'Volume', icon: Package }, { label: 'Other costs', icon: Wallet }, { label: 'Community', icon: Store }, { label: 'Funding', icon: Wallet }];
  if (active.model === 'scott') return <div className="space-y-6"><h1>Scott’s hub model.</h1><ModelSelector /><ScottAssumptions /><ScottFinancials scenario={active} /></div>;
  return <div className="space-y-6"><div><div className="eyebrow">App annual planning engine</div><h1 className="mt-2">Make the numbers work.</h1><p className="mt-2 text-sm text-muted-foreground">Adjust assumptions to explore costs, funding and three-year projections for your active scenario.</p></div>
    <ModelSelector />
    <div className="grid gap-5 xl:grid-cols-[1.8fr_1fr]"><Panel className="overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><h2>Hub assumptions</h2><p className="mt-1 text-xs text-muted-foreground">{active.name} · changes save automatically</p></div><span className="assumption">Editable inputs</span></div><Tabs value={tab} onValueChange={setTab}><TabsList className="flex h-auto flex-wrap justify-start gap-1 rounded-none border-b bg-[#f7f9f3] p-3">{groups.map(g => <TabsTrigger key={g.label} value={g.label} className="gap-1.5 rounded-lg px-3 py-2 text-xs data-[state=active]:bg-white data-[state=active]:text-teal-800 data-[state=active]:shadow-none"><g.icon size={13} />{g.label}</TabsTrigger>)}</TabsList>{groups.map(g => <TabsContent key={g.label} value={g.label} className="m-0 p-5"><div className="grid gap-x-6 gap-y-5 sm:grid-cols-2">{fields.filter(f => f.group === g.label).map(f => <AssumptionInput key={f.key} field={f} />)}</div>{g.label === 'Space' && n(active.inputs, 'sf') > 5000 && <div className="mt-5 flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><AlertTriangle size={16} />Above 5,000 SF: exceeds the team's neighborhood microhub target.</div>}{g.label === 'Funding' && <div className="mt-5 rounded-xl bg-[#edf4ee] p-4 text-xs leading-relaxed text-teal-900">Eligible purchased fleet + charging capex: <b>{money(m.equipment)}</b><br />Grant applied: <b>{money(m.grantApplied)}</b> · capped at eligible equipment.<br />{m.grantEligible ? 'Purchase date is within the eligibility deadline.' : 'Purchase date is after the deadline — no grant applied.'}<br />Grants never offset labor, rent, fit-out, energy or vehicle leases. Verify award and eligibility before relying on funding.</div>}</TabsContent>)}</Tabs></Panel>
    <div className="space-y-5"><Panel className="p-5"><div className="eyebrow">Calculated · app annual engine</div><div className="mt-4 space-y-4">{[['Year 1 startup + operations', money(m.year1Total)], ['Year 2 operating profit', money(m.years[1].profit)], ['Year 3 operating profit', money(m.years[2].profit)], ['Net startup capex', money(m.startup)], ['Operating break-even', m.breakEven ? `Year ${m.breakEven}` : '> 3 years']].map(([label, value]) => <div key={label} className="flex items-center justify-between gap-3 border-b border-border pb-3 text-xs"><span className="text-muted-foreground">{label}</span><span className="text-base font-semibold">{value}</span></div>)}</div></Panel><Panel className="p-5"><h2>One roof. Shared possibilities.</h2><p className="mt-1 text-xs text-muted-foreground">Floor space allocation · calculated SF</p><div className="my-5 flex h-9 overflow-hidden rounded-lg bg-secondary" role="img" aria-label={`${m.logisticsSf} SF logistics, ${m.communitySf} SF community`}>{n(active.inputs, 'sf') > 0 && <><div className="bg-teal-700" style={{ width: `${Math.max(0, m.logisticsSf) / n(active.inputs, 'sf') * 100}%` }} /><div className="bg-[#b6cb8d]" style={{ width: `${Math.min(m.communitySf / n(active.inputs, 'sf') * 100, 100)}%` }} /></>}</div><div className="flex justify-between text-xs"><span className="legend-dot before:bg-teal-700">Logistics <b>{m.logisticsSf.toLocaleString()} SF</b></span><span className="legend-dot before:bg-[#b6cb8d]">Community <b>{m.communitySf.toLocaleString()} SF</b></span></div>{m.logisticsSf < 0 && <p className="mt-3 text-xs font-semibold text-rose-700">Community modules exceed hub area by {Math.abs(m.logisticsSf)} SF. Increase the hub area or reduce module space.</p>}<Button variant="ghost" onClick={() => setTab('Community')} className="mt-4 h-auto p-0 text-xs font-semibold text-teal-800">Configure community uses <ArrowRight size={13} className="ml-2" /></Button></Panel></div></div>
    <Targets inputs={active.inputs} /><Pnl inputs={active.inputs} />
    <Panel className="p-6"><h2>What moves the model?</h2><p className="mt-1 text-xs text-muted-foreground">Sensitivity · ±20% one input at a time, holding everything else fixed. Sliders edit the active assumptions.</p><div className="mt-6 grid gap-8 lg:grid-cols-2"><div className="space-y-6">{[{ key: 'rent', label: 'Annual rent', unit: '$/SF/year', max: 100 }, { key: 'riderRate', label: 'Labor rate (riders)', unit: '$/hour', max: 60 }, { key: 'deliveries', label: 'Deliveries per day', unit: 'deliveries/day', max: 500 }, { key: 'sf', label: 'Hub footprint', unit: 'SF', max: 15000 }].map(s => <div key={s.key}><div className="mb-3 flex justify-between text-xs"><span>{s.label} <span className="text-[9px] text-muted-foreground">· assumption</span></span><b>{n(active.inputs, s.key).toLocaleString()} {s.unit}</b></div><Slider aria-label={s.label} value={[n(active.inputs, s.key)]} onValueChange={v => updateInput(s.key, v[0])} max={Math.max(s.max, n(active.inputs, s.key))} min={0} step={s.key === 'sf' ? 100 : 1} className="[&_[role=slider]]:border-teal-700 [&_span.bg-primary]:bg-teal-700" /></div>)}</div><div><div className="mb-2 text-xs font-semibold">Year 3 profit change · USD</div><Tornado data={sensitivity(active.inputs)} /><p className="text-[10px] text-muted-foreground">Labor sensitivity adjusts all logistics and community hourly rates together. Base profit: {money(m.years[2].profit)}.</p></div></div></Panel>
  </div>;
}
