import ScottFinancials from '@/components/ScottFinancials';
import { Link } from 'react-router-dom';
import { ArrowRight, GitCompareArrows, MapPin, Printer, SlidersHorizontal, CircleHelp } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useWorkspace } from '@/lib/workspace';
import { Kpis, FinanceChart, Targets, Drivers, Panel } from '@/components/Financials';
export default function Index() {
  const { active, data } = useWorkspace();
  if (active.model === 'scott') return <div className="space-y-6"><h1>Your hub, at a glance.</h1><ScottFinancials scenario={active} /><Button asChild className="rounded-xl"><Link to="/model">Edit Scott model assumptions</Link></Button></div>;
  const validations = Object.values(active.metadata).filter(m => m.validation).length;
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">A neighborhood-sized future</div><h1 className="mt-2">Your hub, at a glance.</h1><p className="mt-2 text-sm text-muted-foreground">One place to test the economics. A clearer path to the next B-Line hub.</p></div><div className="no-print flex gap-2"><Button variant="outline" className="action-button" onClick={() => window.print()}><Printer size={14} />Print</Button><Button variant="outline" className="action-button" asChild><Link to="/compare"><GitCompareArrows size={15} />Compare</Link></Button><Button className="rounded-xl text-xs font-semibold" asChild><Link to="/model"><SlidersHorizontal size={15} className="mr-2" />Edit hub model<ArrowRight size={14} className="ml-3" /></Link></Button></div></div>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#dce5d2] bg-[#eef3e7] px-4 py-3"><div className="flex items-center gap-3"><span className="rounded-md bg-white/80 p-1.5 text-teal-700"><MapPin size={17} /></span><div className="text-xs"><span className="font-semibold">{active.name}</span><span className="mx-3 text-[#bbc8af]">/</span><span className="text-muted-foreground">{active.city} · Single neighborhood hub</span></div></div><span className="rounded-full bg-white px-3 py-1 text-[10px] font-medium text-teal-800">Planning scenario</span></div>
    <Kpis inputs={active.inputs} />
    <div className="grid gap-5 xl:grid-cols-[1.9fr_1fr]"><FinanceChart inputs={active.inputs} /><Drivers inputs={active.inputs} /></div>
    <Targets inputs={active.inputs} />
    <div className="no-print grid gap-5 md:grid-cols-2"><Panel className="flex items-start gap-4 p-5"><div className="rounded-xl bg-[#f6efda] p-3 text-[#a17820]"><CircleHelp size={20} /></div><div className="flex-1"><h3 className="text-sm font-semibold">A model is only as good as its inputs.</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{validations} assumptions need validation. Start with rent, rider wages and delivery volume.</p><Link to="/assumptions" className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-teal-800">Review assumptions <ArrowRight size={13} /></Link></div></Panel><Panel className="flex items-start gap-4 p-5"><div className="rounded-xl bg-[#eaf1e6] p-3 text-teal-700"><MapPin size={20} /></div><div><h3 className="text-sm font-semibold">Find the right neighborhood fit.</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{data.sites.length} candidate sites across Seattle and Los Angeles. Compare space, rent and local partnerships.</p><Link to="/sites" className="mt-3 inline-flex items-center gap-2 text-xs font-semibold text-teal-800">Explore candidate sites <ArrowRight size={13} /></Link></div></Panel></div>
  </div>;
}
