import { useState } from 'react';
import { Plus, List, Columns3, Pencil, Trash2, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useWorkspace } from '@/lib/workspace';
import { statuses, type Partner } from '@/lib/defaults';
import { Panel } from '@/components/Financials';
export default function Partners() {
  const { data, setData } = useWorkspace();
  const [city, setCity] = useState('All cities'), [status, setStatus] = useState('All statuses'), [view, setView] = useState('kanban');
  const [editing, setEditing] = useState<Partner | null>(null);
  const filtered = data.partners.filter(p => (city === 'All cities' || p.city === city) && (status === 'All statuses' || p.status === status));
  const updateStatus = (id: string, next: Partner['status']) => setData(w => ({ ...w, partners: w.partners.map(p => p.id === id ? { ...p, status: next } : p) }));
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><div className="eyebrow">Relationships build the network</div><h1 className="mt-2">Keep the conversation moving.</h1><p className="mt-2 text-sm text-muted-foreground">City teams, anchor customers, funders and neighborhood partners.</p></div><Button className="rounded-xl text-xs font-semibold" onClick={() => setEditing({ id: crypto.randomUUID(), org: '', contact: '', role: '', city: 'Seattle', type: 'business partner', status: 'to contact', lastTouch: '', nextStep: '', notes: '' })}><Plus size={15} className="mr-2" />Add partner</Button></div>
    <div className="flex flex-wrap justify-between gap-3"><div className="flex flex-wrap gap-2"><select aria-label="Filter partners by city" className="form-select" value={city} onChange={e => setCity(e.target.value)}>{['All cities', ...new Set(data.partners.map(p => p.city))].map(c => <option key={c}>{c}</option>)}</select><select aria-label="Filter partners by status" className="form-select" value={status} onChange={e => setStatus(e.target.value)}>{['All statuses', ...statuses].map(s => <option key={s}>{s}</option>)}</select><span className="self-center text-xs text-muted-foreground">{filtered.length} partners</span></div><div className="flex gap-1 rounded-lg border bg-white p-1"><Button variant="ghost" size="sm" className={`h-7 rounded-md text-xs ${view === 'kanban' ? 'bg-secondary text-teal-800' : ''}`} onClick={() => setView('kanban')}><Columns3 size={13} className="mr-2" />Board</Button><Button variant="ghost" size="sm" className={`h-7 rounded-md text-xs ${view === 'table' ? 'bg-secondary text-teal-800' : ''}`} onClick={() => setView('table')}><List size={13} className="mr-2" />Table</Button></div></div>
    {view === 'kanban' ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{statuses.map((s, index) => <div key={s} className="min-h-[350px] rounded-2xl border border-border bg-[#eef1ea] p-3"><div className="mb-4 flex items-center justify-between px-1"><h3 className="flex items-center gap-2 text-xs font-semibold capitalize"><span className={`h-2 w-2 rounded-full ${index > 2 ? 'bg-teal-700' : index === 2 ? 'bg-amber-500' : 'bg-[#92a58d]'}`} />{s}</h3><span className="rounded-md bg-white px-2 py-0.5 text-[10px]">{filtered.filter(p => p.status === s).length}</span></div><div className="space-y-3">{filtered.filter(p => p.status === s).map(p => <Panel key={p.id} className="p-3"><div className="flex items-start justify-between"><span className="text-[9px] uppercase tracking-wider text-muted-foreground">{p.city}</span><button aria-label={`Edit ${p.org}`} onClick={() => setEditing({ ...p })}><ArrowUpRight size={13} className="text-muted-foreground" /></button></div><button onClick={() => setEditing({ ...p })} className="mt-2 text-left text-sm font-semibold">{p.org}</button><p className="mt-1 text-[10px] text-muted-foreground">{p.contact || 'Contact to be added'}{p.role && ` · ${p.role}`}</p><span className="mt-3 inline-block rounded-md bg-[#eef4e9] px-2 py-1 text-[9px] text-teal-800">{p.type}</span>{p.nextStep && <p className="mt-3 text-[11px] leading-relaxed">Next: {p.nextStep}</p>}{p.lastTouch && <p className="mt-2 text-[10px] text-muted-foreground">Last touch: {p.lastTouch}</p>}<select className="mt-3 w-full rounded-md border bg-[#fafbf7] p-1.5 text-[10px]" aria-label={`Status for ${p.org}`} value={p.status} onChange={e => updateStatus(p.id, e.target.value as Partner['status'])}>{statuses.map(st => <option key={st}>{st}</option>)}</select></Panel>)}{filtered.every(p => p.status !== s) && <div className="rounded-xl border border-dashed border-[#ced8c9] p-5 text-center text-[11px] text-muted-foreground">No conversations here yet.</div>}</div></div>)}</div> : <Panel className="overflow-x-auto"><table className="data-table min-w-[1150px]"><thead><tr>{['Organization', 'Contact / role', 'City', 'Type', 'Status', 'Last touch', 'Next step', 'Notes', ''].map((h, i) => <th key={i}>{h}</th>)}</tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td className="font-semibold">{p.org}</td><td>{p.contact || '—'}<p className="text-[10px] text-muted-foreground">{p.role}</p></td><td>{p.city}</td><td>{p.type}</td><td><select className="form-select" value={p.status} aria-label={`Status for ${p.org}`} onChange={e => updateStatus(p.id, e.target.value as Partner['status'])}>{statuses.map(s => <option key={s}>{s}</option>)}</select></td><td>{p.lastTouch || '—'}</td><td>{p.nextStep || '—'}</td><td>{p.notes || '—'}</td><td><button onClick={() => setEditing({ ...p })} aria-label={`Edit ${p.org}`}><Pencil size={14} /></button></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-6 text-sm text-muted-foreground">No matching partners.</p>}</Panel>}
    <Dialog open={!!editing} onOpenChange={o => !o && setEditing(null)}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-2xl sm:max-w-xl"><DialogHeader><DialogTitle>Partner conversation</DialogTitle></DialogHeader>{editing && <><div className="grid gap-4 sm:grid-cols-2">{(['org', 'contact', 'role', 'city', 'lastTouch', 'nextStep'] as const).map(key => <label key={key} className="text-xs font-medium capitalize">{key === 'org' ? 'Organization' : key === 'lastTouch' ? 'Last touch' : key === 'nextStep' ? 'Next step' : key}<Input className="mt-1 h-9 rounded-lg" type={key === 'lastTouch' ? 'date' : 'text'} value={editing[key]} onChange={e => setEditing({ ...editing, [key]: e.target.value })} /></label>)}<label className="text-xs">Partner type<select className="form-select mt-1 w-full" value={editing.type} onChange={e => setEditing({ ...editing, type: e.target.value })}>{['City/agency', 'BIA', 'business partner', 'funder', 'developer', 'community'].map(t => <option key={t}>{t}</option>)}</select></label><label className="text-xs">Status<select className="form-select mt-1 w-full" value={editing.status} onChange={e => setEditing({ ...editing, status: e.target.value as Partner['status'] })}>{statuses.map(s => <option key={s}>{s}</option>)}</select></label></div><label className="text-xs">Notes<Textarea className="mt-1 rounded-lg" value={editing.notes} onChange={e => setEditing({ ...editing, notes: e.target.value })} /></label><div className="flex justify-between"><Button variant="ghost" className="text-rose-700" onClick={() => { if (confirm('Delete this partner?')) { setData(w => ({ ...w, partners: w.partners.filter(p => p.id !== editing.id) })); setEditing(null); } }}><Trash2 size={15} /></Button><Button className="rounded-xl" disabled={!editing.org.trim() || !editing.city.trim()} onClick={() => { setData(w => ({ ...w, partners: w.partners.some(p => p.id === editing.id) ? w.partners.map(p => p.id === editing.id ? editing : p) : [...w.partners, editing] })); setEditing(null); }}>Save conversation</Button></div></>}</DialogContent></Dialog>
  </div>;
}
