import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { MapPin, ArrowRight, Plus, Pencil, Printer, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { useWorkspace } from '@/lib/workspace';
import { makeScenario, type Site } from '@/lib/defaults';
import { Panel, Pnl, Kpis } from '@/components/Financials';
import { toast } from 'sonner';
export default function Sites() {
  const { data, setData } = useWorkspace();
  const navigate = useNavigate();
  const [city, setCity] = useState('All cities');
  const [editing, setEditing] = useState<Site | null>(null);
  const [compare, setCompare] = useState<string[]>(['stanford', 'national']);
  const selected = data.sites.filter(s => compare.includes(s.id));
  function model(site: Site) {
    const s = makeScenario(`${site.city === 'Seattle' ? 'Seattle' : 'LA'} – ${site.name}`, site.city, { sf: site.sf || 3000, rent: site.rent }); s.siteId = site.id;
    s.metadata.sf = { source: site.sf ? `Site record: ${site.name}` : 'Area unknown — 3,000 SF planning default', confidence: site.sf ? 'med' : 'low', validation: true };
    s.metadata.rent = { source: `Site record: ${site.name} — verify lease quote`, confidence: 'low', validation: true };
    setData(w => ({ ...w, scenarios: [...w.scenarios, s], activeId: s.id })); navigate('/model'); toast.success('Site scenario created');
  }
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><div className="eyebrow">Location is an assumption, too</div><h1 className="mt-2">A place for the next hub.</h1><p className="mt-2 text-sm text-muted-foreground">Compare candidate sites, local partnerships and neighborhood fit.</p></div><Button className="rounded-xl text-xs font-semibold" onClick={() => setEditing({ id: crypto.randomUUID(), name: '', city: 'Seattle', address: '', sf: 3000, score: 0, neighborhood: '', rent: 24, partner: '', status: 'Site search', notes: 'Rent is an unverified planning assumption.' })}><Plus size={15} className="mr-2" />Add site</Button></div>
    <Panel className="grid gap-5 p-5 md:grid-cols-[1fr_1.4fr]"><div><h2>Seattle neighborhood possibilities</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Source: Cascadia Hub Map · Oct 7, 2026. These are planning areas, not verified properties. Georgetown / South Park is an unconfirmed AI suggestion in the source, not a team decision.</p><p className="mt-4 text-[10px] uppercase tracking-wider text-muted-foreground">Schematic locator · not to scale</p></div><svg viewBox="0 0 520 150" className="w-full" role="img" aria-label="Seattle schematic locator: Capitol Hill, Stadium District, SODO and Georgetown / South Park"><rect x="0" y="0" width="520" height="150" rx="14" fill="#eef2e8" /><path d="M0 0H65L80 50L55 105L70 150H0Z" fill="#d8e7ea" /><path d="M130 25L220 62L300 95L405 125" stroke="#b6c4af" strokeWidth="3" strokeDasharray="5 5" fill="none" />{[[130, 25, 'Capitol Hill'], [220, 62, 'Stadium District'], [300, 95, 'SODO'], [405, 125, 'Georgetown / South Park']].map(([x, y, name], i) => <g key={String(name)}><circle cx={Number(x)} cy={Number(y)} r="6" fill={i === 3 ? '#d4a345' : '#167c68'} /><text x={Number(x) + 13} y={Number(y) - 10} fontSize="11" fill="#345747">{name}</text></g>)}<text x="15" y="130" fontSize="9" fill="#52747b" transform="rotate(-90 15 130)">Elliott Bay</text></svg></Panel>
    <div className="flex flex-wrap items-center justify-between gap-2"><select className="form-select" aria-label="Filter sites by city" value={city} onChange={e => setCity(e.target.value)}>{['All cities', ...new Set(data.sites.map(s => s.city))].map(c => <option key={c}>{c}</option>)}</select><span className="text-xs text-muted-foreground">Select up to 2 sites to compare below · 0 score / SF means unknown</span></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.sites.filter(s => city === 'All cities' || s.city === city).map(site => <Panel className="flex flex-col p-5" key={site.id}><div className="mb-4 flex justify-between"><span className="flex items-center gap-1.5 text-[10px] font-medium uppercase tracking-wide text-teal-800"><MapPin size={13} />{site.city}</span><label className="flex items-center gap-1.5 text-[10px] text-muted-foreground"><input type="checkbox" checked={compare.includes(site.id)} onChange={e => setCompare(c => e.target.checked ? [...c.slice(-1), site.id] : c.filter(id => id !== site.id))} className="accent-teal-700" />Compare</label></div><h2>{site.name}</h2><p className="mt-1 text-xs text-muted-foreground">{site.neighborhood}</p><p className="mt-3 text-[11px] text-muted-foreground">{site.address}</p><div className="my-4 grid grid-cols-3 gap-3 border-y border-border py-4"><div><b className="text-lg">{site.sf ? site.sf.toLocaleString() : 'TBD'}</b><p className="text-[10px] text-muted-foreground">SF · assumption</p></div><div><b className="text-lg">${site.rent}</b><p className="text-[10px] text-muted-foreground">/SF/year · assumption</p></div><div><b className="text-lg">{site.score || '—'}</b><p className="text-[10px] text-muted-foreground">Site score</p></div></div><span className={`w-fit ${site.sf > 5000 || site.status.includes('Unconfirmed') ? 'status-amber' : 'status-green'}`}>{site.sf > 5000 ? 'Above 5,000 SF target' : site.status}</span><p className="my-4 text-xs leading-relaxed text-muted-foreground">{site.notes}</p><div className="mt-auto flex flex-wrap gap-2"><Button className="rounded-lg text-xs" size="sm" onClick={() => model(site)}>Model this site <ArrowRight size={12} className="ml-2" /></Button><Button variant="outline" size="sm" className="rounded-lg text-xs" asChild><Link to={`/sites/${site.id}/proforma`}>Pro forma</Link></Button><Button variant="ghost" size="sm" aria-label={`Edit ${site.name}`} onClick={() => setEditing({ ...site })}><Pencil size={13} /></Button></div></Panel>)}</div>
    {selected.length > 0 && <Panel className="overflow-hidden"><h2 className="p-5">Site comparison</h2><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Site field</th>{selected.map(s => <th key={s.id}>{s.name}</th>)}</tr></thead><tbody>{(['city', 'address', 'neighborhood', 'sf', 'rent', 'score', 'partner', 'status', 'notes'] as const).map(key => <tr key={key}><td className="font-medium">{key === 'sf' ? 'Area · SF' : key === 'rent' ? 'Rent · $/SF/year' : key}</td>{selected.map(s => <td key={s.id}>{s[key] || 'Unknown'}</td>)}</tr>)}</tbody></table></div></Panel>}
    <Dialog open={!!editing} onOpenChange={o => !o && setEditing(null)}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-2xl sm:max-w-xl"><DialogHeader><DialogTitle>{data.sites.some(s => s.id === editing?.id) ? 'Edit candidate site' : 'Add candidate site'}</DialogTitle></DialogHeader>{editing && <><div className="grid gap-4 sm:grid-cols-2">{(['name', 'city', 'address', 'sf', 'score', 'neighborhood', 'rent', 'partner', 'status'] as const).map(key => <label key={key} className="text-xs font-medium">{key === 'sf' ? 'Area (SF; 0 = unknown)' : key === 'rent' ? 'Annual rent ($/SF/year)' : key === 'score' ? 'Score (0 = unassessed)' : key}<Input className="mt-1 h-9 rounded-lg" type={typeof editing[key] === 'number' ? 'number' : 'text'} min={0} value={editing[key]} onChange={e => setEditing({ ...editing, [key]: typeof editing[key] === 'number' ? Math.max(0, Number(e.target.value)) : e.target.value })} /></label>)}</div><label className="text-xs">Notes & source<Textarea className="mt-1 rounded-lg" value={editing.notes} onChange={e => setEditing({ ...editing, notes: e.target.value })} /></label><div className="flex justify-between"><Button variant="ghost" className="text-rose-700" onClick={() => { if (confirm('Delete this site? Existing scenarios will be retained.')) { setData(w => ({ ...w, sites: w.sites.filter(s => s.id !== editing.id) })); setEditing(null); } }}><Trash2 size={15} /></Button><Button disabled={!editing.name.trim() || !editing.city.trim()} className="rounded-xl" onClick={() => { setData(w => ({ ...w, sites: w.sites.some(s => s.id === editing.id) ? w.sites.map(s => s.id === editing.id ? editing : s) : [...w.sites, editing] })); setEditing(null); }}>Save site</Button></div></>}</DialogContent></Dialog>
  </div>;
}
export function SiteProforma() {
  const { id } = useParams(); const { data } = useWorkspace();
  const site = data.sites.find(s => s.id === id);
  const linked = data.scenarios.filter(s => s.siteId === id);
  const [scenarioId, setScenarioId] = useState('');
  if (!site) return <div>Site not found. <Link to="/sites">Return to Sites</Link></div>;
  const scenario = linked.find(s => s.id === scenarioId) ?? linked[0];
  const inputs = scenario?.inputs ?? makeScenario(site.name, site.city, { sf: site.sf || 3000, rent: site.rent }).inputs;
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><div className="eyebrow">Site-specific pro forma</div><h1 className="mt-2">{site.name}</h1><p className="mt-2 text-sm text-muted-foreground">{site.city} · {site.address} · {scenario ? scenario.name : 'Default assumptions with site area and rent'}</p></div><div className="no-print flex flex-wrap gap-2">{linked.length > 0 && <select aria-label="Select site scenario" className="form-select" value={scenario?.id} onChange={e => setScenarioId(e.target.value)}>{linked.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select>}<Button className="rounded-xl" onClick={() => window.print()}><Printer size={15} className="mr-2" />Print pro forma</Button></div></div><Panel className="p-4 text-xs leading-relaxed text-muted-foreground">{site.notes}{!site.sf && <p>Area unknown: using 3,000 SF default for feasibility.</p>}</Panel><Kpis inputs={inputs} /><Pnl inputs={inputs} /></div>;
}
