import { ResponsiveContainer, ComposedChart, Bar, Line, XAxis, YAxis, CartesianGrid, Tooltip, ReferenceLine, BarChart } from 'recharts';
import { ArrowUpRight, Bike, Building2, CalendarCheck, DollarSign, Package, TrendingUp } from 'lucide-react';
import { calculate, money, compactMoney, n, type YearResult } from '@/lib/calc';
import type { Inputs } from '@/lib/defaults';
import { Card } from '@/components/ui/card';
export function Panel({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <Card className={`rounded-2xl border border-border shadow-none ${className}`}>{children}</Card>; }
export function Kpis({ inputs }: { inputs: Inputs }) {
  const m = calculate(inputs);
  const items = [
    { title: 'Year 1 total cost', value: money(m.year1Total), detail: 'Startup + operating costs', icon: DollarSign },
    { title: 'Operating break-even', value: m.breakEven ? `Year ${m.breakEven}` : '> 3 years', detail: 'Annual revenue ≥ costs', icon: CalendarCheck },
    { title: 'Year 3 profit', value: money(m.years[2].profit), detail: 'After profit sharing', icon: TrendingUp },
    { title: 'Cost per delivery', value: m.costPerDelivery === null ? 'N/A' : `$${m.costPerDelivery.toFixed(2)}`, detail: 'Y1 operating costs excl. COGS', icon: Package },
    { title: 'Hub footprint', value: `${n(inputs, 'sf').toLocaleString()} SF`, detail: 'Logistics + community uses', icon: Building2 },
    { title: 'Fleet size', value: `${n(inputs, 'activeCount') + n(inputs, 'reserveCount') + n(inputs, 'vanCount')} vehicles`, detail: `${n(inputs, 'activeCount')} active · ${n(inputs, 'reserveCount')} reserve · ${n(inputs, 'vanCount')} vans`, icon: Bike },
  ];
  return <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-6">{items.map((x, idx) => <Panel key={x.title} className="p-5"><div className="mb-5 flex items-center justify-between"><span className="text-xs font-medium text-muted-foreground">{x.title}</span><x.icon size={17} className="text-teal-700" /></div><div className={`text-[26px] font-semibold tracking-tight ${idx === 2 ? m.years[2].profit >= 0 ? 'text-teal-700' : 'text-rose-700' : ''}`}>{x.value}</div><div className="mt-2 flex items-center gap-2 text-[11px] text-muted-foreground"><span className={`h-1.5 w-1.5 rounded-full ${idx > 3 ? 'bg-amber-500' : 'bg-teal-600'}`} />{x.detail}</div><span className="mt-3 block text-[10px] uppercase tracking-widest text-muted-foreground">{idx > 3 ? 'Assumption' : 'Calculated'}</span></Panel>)}</div>;
}
export function FinanceChart({ inputs }: { inputs: Inputs }) {
  const m = calculate(inputs);
  return <Panel className="p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2>Three-year financial outlook</h2><p className="mt-1 text-xs text-muted-foreground">Revenue, operating costs & cumulative cash · USD</p></div><span className="calculated">Calculated result</span></div><div className="mb-2 mt-5 flex flex-wrap gap-5 text-xs"><span className="legend-dot before:bg-teal-700">Revenue</span><span className="legend-dot before:bg-[#c6d4cc]">Operating costs</span><span className="legend-dot before:bg-amber-500">Cumulative cash</span></div><div className="h-[285px] w-full"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={m.years} margin={{ top: 20, right: 8, left: 0, bottom: 0 }}><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#e7ece8" /><XAxis dataKey="year" axisLine={false} tickLine={false} tick={{ fontSize: 12, fill: '#66736d' }} tickFormatter={v => `Year ${v.slice(1)}`} /><YAxis tickFormatter={compactMoney} axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: '#66736d' }} width={62} /><Tooltip formatter={(value: number) => money(value)} contentStyle={{ borderRadius: 12, borderColor: '#e2e8e4', fontSize: 12 }} /><ReferenceLine y={0} stroke="#aebbb2" /><Bar dataKey="revenue" name="Revenue" fill="#147b68" radius={[5, 5, 0, 0]} maxBarSize={54} /><Bar dataKey="costs" name="Operating costs" fill="#c6d4cc" radius={[5, 5, 0, 0]} maxBarSize={54} /><Line dataKey="cumulative" name="Cumulative cash" stroke="#d6a139" strokeWidth={2.5} dot={{ r: 4, strokeWidth: 2, fill: '#fff' }} /></ComposedChart></ResponsiveContainer></div></Panel>;
}
export function Targets({ inputs }: { inputs: Inputs }) {
  const m = calculate(inputs), profit = m.years[2].profit;
  const targets = [
    { label: 'Year 1 launch budget', target: 'Target: approximately $500k', actual: money(m.year1Total), state: m.year1Total <= 500000 ? 'green' : m.year1Total <= 550000 ? 'amber' : 'red', note: 'Startup capex + full Year 1 costs; grants deducted' },
    { label: 'Year 2 break-even', target: 'Target: operating profit ≥ $0', actual: money(m.years[1].profit), state: m.years[1].profit >= 0 ? 'green' : m.years[1].profit >= -50000 ? 'amber' : 'red', note: 'Annual revenue covers operating costs' },
    { label: 'Year 3 modest profit', target: 'Planning band: $10k–$100k', actual: money(profit), state: profit >= 10000 && profit <= 100000 ? 'green' : profit >= 0 ? 'amber' : 'red', note: profit > 100000 ? 'Above planning band — validate assumptions' : 'After damaged goods & profit sharing' },
  ];
  return <Panel className="p-6"><div className="mb-5 flex items-center justify-between"><h2>Against our targets</h2><span className="text-xs text-muted-foreground">The single-hub test</span></div><div className="grid gap-5 md:grid-cols-3">{targets.map(t => <div key={t.label} className="rounded-xl border border-border bg-[#fafbf8] p-4"><div className="flex items-center justify-between gap-2 text-sm font-medium">{t.label}<span className={`status-${t.state}`}>{t.state === 'green' ? 'On track' : t.state === 'amber' ? 'Review' : 'Off track'}</span></div><div className="my-3 text-2xl font-semibold">{t.actual}</div><div className="text-xs font-medium text-muted-foreground">{t.target}</div><p className="mt-2 text-[11px] text-muted-foreground">{t.note}</p></div>)}</div></Panel>;
}
export function Drivers({ inputs }: { inputs: Inputs }) {
  const m = calculate(inputs);
  return <Panel className="p-6"><h2>Biggest cost drivers</h2><p className="mb-5 mt-1 text-xs text-muted-foreground">Where Year 1 operating dollars go</p><div className="space-y-5">{m.drivers.slice(0, 4).map((d, i) => <div key={d.name}><div className="mb-2 flex justify-between text-xs"><span><span className="mr-2 text-muted-foreground">0{i + 1}</span>{d.name}</span><span className="font-semibold">{money(d.value)} <span className="font-normal text-muted-foreground">· {m.years[0].costs ? (d.value / m.years[0].costs * 100).toFixed(0) : 0}%</span></span></div><div className="h-2 rounded-full bg-secondary"><div className={`h-full rounded-full ${i === 0 ? 'bg-teal-700' : 'bg-[#99b5a5]'}`} style={{ width: `${m.years[0].costs ? d.value / m.years[0].costs * 100 : 0}%` }} /></div></div>)}</div><div className="mt-6 rounded-xl bg-[#eef5ee] p-3 text-xs leading-relaxed text-teal-900"><ArrowUpRight className="mb-1 inline" size={14} /> {m.drivers[0].name} and {m.drivers[1].name.toLowerCase()} account for {m.years[0].costs ? ((m.drivers[0].value + m.drivers[1].value) / m.years[0].costs * 100).toFixed(0) : 0}% of operating costs. Test these assumptions first.</div></Panel>;
}
export function Pnl({ inputs }: { inputs: Inputs }) {
  const m = calculate(inputs);
  const rows: [string, keyof YearResult][] = [['Logistics revenue', 'logisticsRevenue'], ['Community revenue', 'communityRevenue'], ['Total revenue', 'revenue'], ['Rent & occupancy', 'rent'], ['Labor incl. payroll burden', 'labor'], ['Fleet operations & leases', 'fleet'], ['Software & utilities', 'other'], ['Community COGS', 'cogs'], ['Damaged goods †', 'damage'], ['Profit sharing †', 'sharing'], ['Total operating costs', 'costs'], ['Operating profit', 'profit'], ['Cumulative cash', 'cumulative']];
  return <Panel className="overflow-hidden"><div className="flex flex-wrap justify-between gap-2 p-6"><div><h2>Three-year profit & loss</h2><p className="mt-1 text-xs text-muted-foreground">Operating model · USD · calculated results</p></div><span className="calculated">Cash-basis planning</span></div><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Line item · USD</th>{m.years.map(y => <th key={y.year} className="text-right">Year {y.year.slice(1)}</th>)}</tr></thead><tbody>{rows.map(([label, key]) => <tr key={key} className={['revenue', 'costs', 'profit', 'cumulative'].includes(key) ? 'font-semibold bg-[#f6f8f4]' : ''}><td>{label}</td>{m.years.map(y => <td key={y.year} className={`text-right tabular-nums ${key === 'profit' ? y.profit >= 0 ? 'text-teal-700' : 'text-rose-700' : ''}`}>{money(Number(y[key]))}</td>)}</tr>)}<tr><td>Net startup capex (Year 0)</td><td className="text-right">{money(m.startup)}</td><td className="text-right">—</td><td className="text-right">—</td></tr></tbody></table></div><div className="flex flex-wrap gap-6 p-5 text-xs text-muted-foreground"><span>Operating break-even: <b className="text-foreground">{m.breakEven ? `Year ${m.breakEven}` : 'Not within 3 years'}</b></span><span>Cash payback: <b className="text-foreground">{m.payback ? `Year ${m.payback}` : 'Not within 3 years'}</b></span><p className="w-full text-[11px]">† Assumption — needs validation. Cash includes net startup investment, no financing, taxes, depreciation or salvage. Operating costs escalate annually; revenue follows the volume ramp. Cost/delivery includes shared staffing and excludes community COGS; it is a blended hub metric.</p></div></Panel>;
}
export function Tornado({ data }: { data: ReturnType<typeof import('@/lib/calc').sensitivity> }) {
  return <div className="h-[225px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" stackOffset="sign" margin={{ left: 0, right: 30, bottom: 0 }}><CartesianGrid horizontal={false} strokeDasharray="3 3" /><XAxis type="number" tickFormatter={compactMoney} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="name" width={110} tick={{ fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip formatter={(v: number) => money(v)} /><ReferenceLine x={0} stroke="#768d82" /><Bar dataKey="low" name="Lower profit delta" stackId="s" fill="#d6ad58" radius={3} /><Bar dataKey="high" name="Higher profit delta" stackId="s" fill="#16846c" radius={3} /></BarChart></ResponsiveContainer></div>;
}
