import { useState } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, Calculator, FileSpreadsheet } from 'lucide-react';
import { Panel } from '@/components/Financials';
import { liveEngineLabel, modelSources } from '@/lib/modelSources';

export default function ModelSourceRegister() {
  const [sourceId, setSourceId] = useState('scott');
  const selected = modelSources.find(source => source.id === sourceId)!;
  return <Panel className="overflow-hidden">
    <div className="border-b border-border bg-teal-50/60 p-5"><div className="flex items-center gap-2"><BookOpen size={19} className="text-teal-700" /><h2>Model & data-source register</h2></div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">One place to identify the team’s models, what this app actually uses, and what still needs alignment. Owner labels for Scott and LACI reflect the team’s naming.</p></div>
    <div className="grid gap-4 p-5 lg:grid-cols-2"><div className="rounded-xl border border-teal-200 p-4"><div className="flex items-center gap-2 text-teal-800"><Calculator size={17} /><h3 className="text-sm font-semibold">Original calculation engine: {liveEngineLabel}</h3></div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Scenarios can use either the app annual engine or Scott’s CSV reconstruction. The selected model is shown with its projections. LACI and Seattle monthly PDF outputs remain references, not editable engines.</p><Link className="mt-3 inline-block text-xs font-semibold text-teal-800 underline underline-offset-4" to="/assumptions">Inspect active input sources & confidence</Link></div>
    <div className="rounded-xl border border-border p-4"><label htmlFor="reference-model" className="text-xs font-semibold">Select a reference to inspect</label><select id="reference-model" value={sourceId} onChange={e => setSourceId(e.target.value)} className="form-select mt-2 w-full">{modelSources.map(source => <option key={source.id} value={source.id}>{source.name} — {source.owner}</option>)}</select><p className="mt-2 text-[11px] text-muted-foreground">Reference selection only. This does not change formulas, inputs or the active scenario.</p></div></div>
    <div className="mx-5 mb-5 rounded-xl bg-secondary/60 p-4" aria-live="polite"><div className="flex items-start gap-2"><FileSpreadsheet size={18} className="mt-0.5 shrink-0 text-teal-700" /><div><h3 className="text-sm font-semibold">{selected.name} · {selected.owner}</h3><p className="mt-1 text-[11px] font-semibold text-teal-800">{selected.status}</p><p className="mt-3 text-xs leading-relaxed">{selected.use}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground"><b>Assumptions / open questions:</b> {selected.assumptions}</p></div></div></div>
    <div className="overflow-x-auto"><table className="data-table min-w-[900px]"><thead><tr><th>Source / model</th><th>Owner / label</th><th>Type</th><th>Use in this app</th></tr></thead><tbody>{modelSources.map(source => <tr key={source.id}><td className="font-medium">{source.name}</td><td>{source.owner}</td><td>{source.kind}</td><td><p className="font-semibold">{source.status}</p><p className="mt-1 text-muted-foreground">{source.use}</p></td></tr>)}</tbody></table></div>
    <p className="p-5 text-xs leading-relaxed text-muted-foreground">No spreadsheet, CRM, market-data or external financial API is automatically connected. JSON import replaces browser-saved workspace records; it does not connect a workbook. Before adopting a baseline, the team should confirm the accountable owner, exact file/version, approved input sources and reconciled output definitions. Matt’s source/model has not been identified here yet.</p>
  </Panel>;
}
