import { Panel } from '@/components/Financials';
import { calculateScott, scottLabel, scottState } from '@/lib/scottModel';
import { money } from '@/lib/calc';
import type { Scenario } from '@/lib/defaults';

export default function ScottFinancials({ scenario }: { scenario: Scenario }) {
  const state = scottState(scenario), m = calculateScott(state.inputs);
  const rows = [['Delivery revenue',Number(state.inputs.delivery)],['Advertising & promotion',Number(state.inputs.promo)],['Total annual revenue',m.revenue],['Delivery labor',Number(state.inputs.deliveryLabor)],['Operating expenses · including rent',m.opex],['Profit before sharing',m.beforeShare],['Profit share · positive profit only',m.sharing],['Profit after sharing',m.afterShare]] as const;
  return <div className="space-y-5"><div><h2>{scottLabel}</h2><p className="mt-1 text-xs text-muted-foreground">{scenario.name} · editable annual module economics and separate funding targets.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Annual revenue',m.revenue],['Annual profit after sharing',m.afterShare],['Total funding uses',m.uses],['Unfunded uses · negative = surplus',m.fundingGap]].map(([label,value]) => <Panel key={label} className="p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-3 text-xl font-semibold">{money(Number(value))}</p></Panel>)}</div>
    <div className="grid gap-5 lg:grid-cols-2"><Panel className="overflow-x-auto"><h2 className="p-5">1-Hub operating economics · annual</h2><table className="data-table"><tbody>{rows.map(([label,value]) => <tr key={label}><td>{label}</td><td className="text-right font-semibold">{money(value)}</td></tr>)}</tbody></table><p className="p-5 text-xs text-muted-foreground">After-share margin: {m.revenue ? `${(m.afterShare/m.revenue*100).toFixed(2)}%` : 'Not applicable · no revenue'}. Monthly figures are annual ÷ 12, not a ramped cash-flow forecast.</p></Panel>
    <Panel className="overflow-x-auto"><h2 className="p-5">S+U targets · not operating forecasts</h2><table className="data-table"><thead><tr><th>Year</th><th>Revenue target</th><th>Profit target · pre-share</th></tr></thead><tbody>{m.targets.map(y => <tr key={y.year}><td>Year {y.year}</td><td>{money(y.revenue)}</td><td>{money(y.profit)}</td></tr>)}</tbody></table><p className="p-5 text-xs leading-relaxed text-muted-foreground">Profit targets = each revenue target × {String(state.inputs.targetMargin)}%. These do not apply the 1-Hub cost lines or predict cash burn. No later-year operating expense, depreciation or IRR formulas were supplied.</p></Panel></div>
    <Panel className="p-5"><h2>Occupancy & funding</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Break-even occupancy / month',m.breakEvenMonthly],['Target-margin occupancy / month',m.targetMonthly],['Sources · grant remains an assumption',m.sources],['Uses',m.uses]].map(([label,value]) => <div key={label}><p className="text-[11px] text-muted-foreground">{label}</p><b className="mt-2 block">{money(Number(value))}</b></div>)}</div><p className="mt-4 text-xs text-muted-foreground">Negative occupancy ceilings mean the target cannot be reached even with free space. Grants are entered funding assumptions, not confirmed awards or eligibility calculations. Ramp costs and working capital are funding uses, not added again to annual operating costs.</p></Panel>
  </div>;
}
