import { useRef, useState } from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { LayoutDashboard, SlidersHorizontal, MapPin, Users, BookOpen, ArrowDownToLine, Upload, ChevronDown, Plus, Copy, Pencil, Trash2, GitCompareArrows, Menu, X, Check, Leaf } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { useWorkspace, download, parseWorkspace } from '@/lib/workspace';
import { makeScenario } from '@/lib/defaults';
import { toast } from 'sonner';
import SourceNotice from '@/components/SourceNotice';
const links = [{ to: '/', label: 'Sites', icon: MapPin }, { to: '/dashboard', label: 'Dashboard', icon: LayoutDashboard }, { to: '/model', label: 'Hub Model', icon: SlidersHorizontal }, { to: '/map', label: 'Cascadia Map', icon: MapPin }, { to: '/sources', label: 'Source Scorecard', icon: BookOpen }, { to: '/partners', label: 'Partners & Outreach', icon: Users }, { to: '/assumptions', label: 'Assumptions Log', icon: BookOpen }];
export default function WorkspaceLayout() {
  const { data, setData, active } = useWorkspace();
  const navigate = useNavigate();
  const file = useRef<HTMLInputElement>(null);
  const [mobile, setMobile] = useState(false);
  const [action, setAction] = useState<'new' | 'rename' | 'duplicate' | null>(null);
  const [name, setName] = useState('');
  const openAction = (a: typeof action) => { setName(a === 'rename' ? active.name : a === 'duplicate' ? `${active.name} – copy` : 'New neighborhood hub'); setAction(a); };
  const saveScenario = () => {
    if (!name.trim()) return;
    if (action === 'rename') setData(w => ({ ...w, scenarios: w.scenarios.map(s => s.id === active.id ? { ...s, name: name.trim() } : s) }));
    else {
      const scenario = action === 'duplicate' ? { ...structuredClone(active), id: crypto.randomUUID(), name: name.trim() } : makeScenario(name.trim());
      setData(w => ({ ...w, activeId: scenario.id, scenarios: [...w.scenarios, scenario] }));
    }
    setAction(null); toast.success('Scenario saved');
  };
  return <div className="min-h-screen bg-background">
    {mobile && <div className="fixed inset-0 z-30 bg-teal-950/30 lg:hidden" onClick={() => setMobile(false)} />}
    <aside className={`no-print fixed inset-y-0 left-0 z-40 flex w-[232px] flex-col overflow-y-auto border-r border-border bg-[#fcfcf7] transition-transform lg:translate-x-0 ${mobile ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="px-5 pb-7 pt-6"><NavLink to="/" onClick={() => setMobile(false)} aria-label="B-Line Urban Delivery — Sites home" className="block rounded-2xl bg-teal-900 px-4 py-5 transition-colors hover:bg-teal-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-600 focus-visible:ring-offset-2"><img src="https://b-linepdx.com/wp-content/uploads/Approved-B-Line-Urban-Delivery-white-logo-with-strapline.png" alt="B-Line Urban Delivery" className="h-auto w-full object-contain" /></NavLink><div className="mt-5 text-[11px] font-medium text-muted-foreground">MICROHUB PLANNER <span className="ml-2 rounded bg-[#ecefe8] px-1.5 py-0.5 text-[9px]">V1</span></div></div>
      <div className="px-5 text-[9px] font-semibold uppercase tracking-[1.8px] text-muted-foreground">Workspace</div>
      <nav className="mt-3 space-y-1 px-3">{links.map(l => <NavLink key={l.to} to={l.to} end={l.to === '/'} onClick={() => setMobile(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-4 py-3 text-[13px] font-medium ${isActive ? 'bg-[#e8eedf] text-teal-900' : 'text-muted-foreground hover:bg-secondary hover:text-foreground'}`}><l.icon size={18} strokeWidth={1.8} />{l.label}</NavLink>)}</nav>
      <div className="mt-8 px-5 text-[9px] font-semibold uppercase tracking-[1.8px] text-muted-foreground">Your scenarios <span className="float-right">{data.scenarios.length}</span></div>
      <div className="mt-3 max-h-[220px] space-y-1 overflow-y-auto px-4">{data.scenarios.map(s => <button key={s.id} onClick={() => setData(w => ({ ...w, activeId: s.id }))} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs ${active.id === s.id ? 'font-semibold text-teal-800' : 'text-muted-foreground hover:bg-secondary'}`}><span className={`h-1.5 w-1.5 shrink-0 rounded-full ${active.id === s.id ? 'bg-teal-700' : 'bg-[#bac6b9]'}`} /><span className="truncate">{s.name}</span>{active.id === s.id && <Check size={12} className="ml-auto shrink-0" />}</button>)}</div>
      <button onClick={() => openAction('new')} className="mx-7 mt-3 flex items-center gap-2 text-xs text-muted-foreground hover:text-teal-700"><Plus size={14} /> New scenario</button>
      <div className="mt-auto p-4"><div className="rounded-xl border border-[#dce5d8] bg-[#f2f5ed] p-4"><Leaf size={18} className="mb-2 text-teal-700" /><p className="text-xs font-semibold">Small hubs. Big possibility.</p><p className="mt-1.5 text-[11px] leading-relaxed text-muted-foreground">Building the next chapter of neighborhood logistics.</p></div><div className="mt-5 flex items-center gap-2 px-1"><div className="flex -space-x-1.5">{['FJ', 'M', 'J', 'S'].map((s, i) => <div key={s} className={`flex h-6 w-6 items-center justify-center rounded-full border-2 border-[#fcfcf7] text-[8px] font-semibold ${i === 0 ? 'bg-[#c7d6ad]' : 'bg-[#e0e6db]'}`}>{s}</div>)}</div><span className="text-[10px] text-muted-foreground">B-Line team · Internal only</span></div></div>
    </aside>
    <div className="lg:ml-[232px]"><header className="no-print flex min-h-[76px] flex-wrap items-center justify-between gap-3 border-b border-border bg-[#fcfcf8] px-5 py-4 lg:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobile(!mobile)} className="lg:hidden" aria-label="Toggle navigation">{mobile ? <X size={20} /> : <Menu size={20} />}</button><span className="hidden text-xs text-muted-foreground sm:block">Active scenario</span><div className="relative"><select aria-label="Active scenario" className="max-w-[240px] appearance-none rounded-lg border border-border bg-white py-2 pl-3 pr-8 text-xs font-semibold outline-none focus:ring-2 focus:ring-teal-600" value={active.id} onChange={e => setData(w => ({ ...w, activeId: e.target.value }))}>{data.scenarios.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select><ChevronDown size={13} className="pointer-events-none absolute right-3 top-3" /></div><span className="hidden items-center gap-1 text-[10px] text-muted-foreground xl:flex"><span className="h-1.5 w-1.5 rounded-full bg-teal-600" /> Saved locally</span></div><div className="flex items-center gap-2"><Button variant="outline" size="sm" className="action-button" onClick={() => file.current?.click()}><Upload size={14} />Import</Button><Button variant="outline" size="sm" className="action-button" onClick={() => download('b-line-workspace.json', JSON.stringify(data, null, 2))}><ArrowDownToLine size={14} />Export JSON</Button><div className="ml-2 hidden h-8 w-8 items-center justify-center rounded-full bg-[#e3e9d6] text-[11px] font-semibold sm:flex">FJ</div></div>
      <input ref={file} type="file" accept="application/json,.json" className="hidden" onChange={async e => { const f = e.target.files?.[0]; if (!f) return; try { if (f.size > 5e6) throw new Error('Too large'); const imported = parseWorkspace(await f.text()); if (confirm('Replace this browser’s workspace with the imported data? Export your current work first if needed.')) { setData(imported); toast.success('Workspace imported'); } } catch { toast.error('Invalid workspace file. Import a complete B-Line v1 JSON export (under 5 MB).'); } e.target.value = ''; }} /></header>
      <main className="mx-auto max-w-[1700px] px-5 py-7 lg:px-8"><SourceNotice /><Outlet /><div className="no-print mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-border py-4 text-[10px] text-muted-foreground"><span>Freeroot Ventures DBA B-Line · Internal planning tool</span><span>All figures are planning assumptions until validated. No data leaves this browser.</span></div></main>
      <div className="no-print fixed bottom-4 right-5 flex gap-1 rounded-xl border border-border bg-white p-1.5 shadow-lg"><Button variant="ghost" size="sm" title="Rename scenario" aria-label="Rename scenario" onClick={() => openAction('rename')}><Pencil size={15} /></Button><Button variant="ghost" size="sm" title="Duplicate scenario" aria-label="Duplicate scenario" onClick={() => openAction('duplicate')}><Copy size={15} /></Button><Button variant="ghost" size="sm" title="Compare scenarios" aria-label="Compare scenarios" onClick={() => navigate('/compare')}><GitCompareArrows size={15} /></Button><Button variant="ghost" size="sm" title="Delete scenario" aria-label="Delete scenario" disabled={data.scenarios.length < 2} onClick={() => { if (confirm(`Delete “${active.name}”? This cannot be undone.`)) setData(w => { const scenarios = w.scenarios.filter(s => s.id !== active.id); return { ...w, scenarios, activeId: scenarios[0].id }; }); }}><Trash2 size={15} /></Button></div>
    </div>
    <Dialog open={!!action} onOpenChange={o => !o && setAction(null)}><DialogContent className="rounded-2xl sm:max-w-md"><DialogHeader><DialogTitle>{action === 'rename' ? 'Rename scenario' : action === 'duplicate' ? 'Duplicate scenario' : 'Create a scenario'}</DialogTitle></DialogHeader><label className="text-xs text-muted-foreground" htmlFor="scenario-name">Scenario name</label><Input id="scenario-name" value={name} onChange={e => setName(e.target.value)} maxLength={120} onKeyDown={e => e.key === 'Enter' && saveScenario()} /><Button className="rounded-xl font-semibold" disabled={!name.trim()} onClick={saveScenario}>Save scenario</Button></DialogContent></Dialog>
  </div>;
}
